### ISSUE TITLE
モデルデータ解析中に「QColor::setRgb: RGB parameters out of range」と表示される

### ISSUE THREAD

**Issue by ikanohito** [miu200521358/vmd_sizing#1]
材質モーフは負の数値やRGBの値範囲を超えた数値を取ることもあるため、モデルによって表示されることがある…という事態が発生します。

**Comment by miu200521358** [comment]
ご指摘ありがとうございます。
β34で対応いたしました。
https://github.com/miu200521358/vmd_sizing/commit/925aafe95ee1872d796d27fdafacb77392f1eb22
