### ISSUE TITLE
禁止事項がGPLのライセンスと矛盾する / prohibitions contradict to GPL

### ISSUE THREAD

**Issue by ddmer** [miu200521358/vmd_sizing#20]
ライセンスにGPLを採用する場合、利用者に対する用途の制限を設けてはならないが、README.md の禁止事項はこれに矛盾する。
https://github.com/miu200521358/vmd_sizing/blob/master/LICENSE
https://github.com/miu200521358/vmd_sizing#%E7%A6%81%E6%AD%A2%E4%BA%8B%E9%A0%85

**Comment by lo48576** [comment]
一般に、プログラムの出力がプログラム自身の複製や内部的なリソースのコピーを埋め込むのでない限り、その出力について特別に利用制限を設けることはできないように思われます (IANAL, TINLA)。

少なくとも、そのような出力の利用制限は GPL-3 と矛盾するはずです。

> ### わたしのコードをGPLでライセンスしたいと思いますが、軍事利用や商用利用をさせないようにはっきりしたいと考えています。これは可能ですか? (#NoMilitary)
>
> いいえ、その二つの目的は互いに矛盾しますから。GNU GPLは、さらなる制限を加えることを妨げるよう特に設計されています。GPLv3は、第7節で、とても限定された制限の追加を認めていますが、そのほかのあらゆる加えられた制限はユーザによって削除されることが可能です。
>
> --- [GNUライセンスに関してよく聞かれる質問 - GNUプロジェクト - フリーソフトウェアファウンデーション](https://www.gnu.org/licenses/gpl-faq.ja.html#NoMilitary)

> ### 研究論文でGPLの及ぶソフトウェアとその出力を使った際に、引用や謝辞を要求する条項を追加することを、GPLは、許可していますか?(#RequireCitation)
>
> (中略) そして、GPLの条項でライセンスされているか、ほかのライセンスでかに関係なく、著作権法は、そのように[ソフトウェアの出力への要求](https://www.gnu.org/licenses/gpl-faq.ja.html#GPLOutput)を認めていません。
>
> --- [GNUライセンスに関してよく聞かれる質問 - GNUプロジェクト - フリーソフトウェアファウンデーション](https://www.gnu.org/licenses/gpl-faq.ja.html#RequireCitation)

> ### 人々がわたしのプログラムを利用して得た出力結果にGPLを適用する方法はないでしょうか? たとえば、わたしのプログラムがハードウェアの設計に使われているとして、その設計図も自由でなければならないと要求することはできるでしょうか? (#GPLOutput)
>
> 一般的に言って、それは法的に不可能です。著作権法は人々があなたのプログラムとかれらのデータを使って作った出力結果の利用に関して、あなたに何の発言権も与えていません。ユーザがあなたのプログラムを使ってその人自身のデータを入力ないし変換した場合、出力結果の著作権はその人に属すのであって、あなたにではありません。もっと一般的に言えば、あるプログラムが入力を他の形式に変換する場合、出力結果の著作権の状態は、生成の元となった入力のそれを継承するのです。
>
> --- [GNUライセンスに関してよく聞かれる質問 - GNUプロジェクト - フリーソフトウェアファウンデーション](https://www.gnu.org/licenses/gpl-faq.ja.html#GPLOutput)

**Comment by miu200521358** [comment]
ライブラリを変更し、MITライセンスに変更しました。
