### ISSUE TITLE
Wiki修正

### ISSUE THREAD

**Issue by kaorin** [miu200521358/vmd_sizing#29]
Wiki修正しましたが、pull reqを送る方法がないようですので、URLだけ貼っておきます。
https://github.com/kaorin/vmd_sizing/wiki/02.-%E4%BD%BF%E3%81%84%E6%96%B9

加えて、使い方の [B01. スタンス追加補正]、 [B02. 捩り分散] のドキュメントが存在しないようです。

**Comment by miu200521358** [comment]
修正ありがとうございます。
URLだと比較ができないので、取り込んでいいかの判断が出来ずすみません。
Wikiは修正途中なのであちこち不足していると思います。
随時対応していきます。ありがとうございました。
